### ISSUE TITLE
bitty 易用性改进

### ISSUE THREAD

**Issue by chunqian** [paladin-t/bitty#32]
我对bitty做了大量的易用性和UI方面的改进 
一部分的演示: 

https://user-images.githubusercontent.com/13447930/168944534-c870582e-9301-44e0-91ce-354554372cfb.mp4 

其中一些修改了第三方包, imgui_code_editor, imgui这些包都有改动 
暂时没有提交pr

**Comment by chunqian** [comment]
@paladin-t 
[bitty修改版](https://github.com/chunqian/bitty)在main主分支上 
我有计划做bitty, golang port的实现 
itch.io买了一份支持下 
bitty真的挺好, 只是c++不是我的主修, 没办法太深入 
还有xcode上不要使用gnu11 gnu++14编译, 会导致随机启动crash 
xcode编译使用c99 c++14

**Comment by paladin-t** [comment]
感谢支持。等我空一些仔细看你加的新功能。
期待 golang port，有进展务必告知。
