### ISSUE TITLE
"open"/"save" silently do nothing, itch.io paid download

### ISSUE THREAD

**Issue by lygaret** [paladin-t/bitty#40]
I think I've got a bug, but there's not a lot to go on - no matter what I do, I can't get "open" or "save" to do anything; opening from examples works, but "open", "open from directory", and all the save options just silently do nothing.

This is the itch.io pro download on linux x64

1. run bitty (sorry I accidentally changed workspaces)
1. prove the app works, it runs
1. try to save, nothing happens
1. try to save as, nothing happens
1. try to save as directory, nothing happens
1. quit, asked to save, nothing happens

https://youtu.be/Lhp5JfAd06I

​Happy to get anything else that would be helpful!
​​

**Comment by paladin-t** [comment]
Hello,

Bitty Engine requires one of the following package to show file dialogs:

- zenity
- kdialog
- matedialog
- qarma

Please make sure some of these are available, and let me know if the problem remains.

**Comment by lygaret** [comment]
Yep that did it, thanks! I'd recommend adding something about that to the installation instructions for linux; it's mentioned in the manual, but only as a requirement for building projects for desktop.

**Comment by lygaret** [comment]
Actually, a popup in the workspace when trying something for which a tool can't be found would be best, because then I would have known what I needed to add. As it is, it feels like a bug, regardless of documentation.

Loving the project, just some thoughts.

**Comment by paladin-t** [comment]
Yep, it's better to give a notice than ignore in silence. Will make an update to show a popup for it.

**Comment by paladin-t** [comment]
Added a notice in v1.2.2
