### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by ryanford** [paladin-t/bitty#41]
Are games made with Bitty required to be GPL licensed because of the dependency on Mongoose?

**Comment by paladin-t** [comment]
Licenses of the components of the software don't affect generated data and games.

**Comment by ryanford** [comment]
I'm not a lawyer, and this isn't legal advice, but I'm pretty sure that is incorrect. If bitty is producing executables that include mongoose, than those programs would be subject to the license of mongoose. [If a library is released under the GPL not the LGPL, does that mean that any program which uses it has to be under the GPL?](https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.html#TOCIfLibraryIsGPL)

**Comment by paladin-t** [comment]
It will switch to other commercial-friendly backends.
